[api]
host = '0.0.0.0'
port = 8080
log_level = 'info'

[mqtt]
broker = '192.168.0.36'
port = 1883
client_id = 'ble_to_mqtt_bridge'
keep_alive_secs = 5
topic = 'living_room/air_quality/data'

[ble]
enable_scan = true
scan_auto_start = true